apiVersion: v1
kind: PersistentVolume
metadata:
  name: lv-nfs-vol2
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce  
  nfs:
    path: /mnt/nfs-shares/lv-nfs-vol2
    server: 192.168.1.101
    readOnly: false