apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvnginx
spec:
  selector:
    matchLabels:
      app: lvnginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lvnginx
    spec:
      containers:
      - name: lvrocky91
        image: lalindrait/lvrocky91:1.0
        ports:
        - containerPort: 8080
