kind: Pod
apiVersion: v1
metadata:
  name: pv-nginx
  labels:
    app: nginx
spec:
  containers:
  - name: pvnginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: lv-nfs-vol1
      mountPath: /mnt
  nodeSelector:
    hostname: worker-1
  volumes:
  - name: lv-nfs-vol1
    nfs:
      server: 192.168.1.101
      path: /mnt/nfs-shares/lv-nfs-vol1
      readOnly: false