kind: Pod
apiVersion: v1
metadata:
  name: lvnginx1
  labels:
    app: lvnginx1
spec:
  containers:
  - name: lvnginx
    image: lalindrait/lvnginx:1.0
    ports:
    - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-1
