apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lv-nginx-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lv-web
  serviceName: lvappsvc
  template:
    metadata:
      labels:
        app: lv-web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: lv-web
          image: lalindrait/lvrocky91:latest
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - name: lv-local-vol1
            mountPath: /usr/share/nginx/lv-mnt
      volumes:
      - name: lv-local-vol1
        persistentVolumeClaim:
          claimName: lv-local-claim



          