kind: Pod
apiVersion: v1
metadata:
  name: pv-nginx
  labels:
    app: nginx
spec:
  containers:
  - name: pvnginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: lv-nfs-vol3
      mountPath: /mnt
  volumes:
  - name: lv-nfs-vol3
    persistentVolumeClaim:
        claimName: lv-nfs-vol3-claim