apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lv-web
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lv-web
    spec:
      containers:
      - name: lvnginx
        image: lalindrait/lvnginx:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256M"
            cpu: "1000m"
          limits:
            memory: "512M"
            cpu: "2000m"
