apiVersion: v1
kind: Pod
metadata:
  name: lv-nginx-multipod
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: lvnginx
    image: lalindrait/lvnginx:1.0
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: lvrocky
    image: lalindrait/lvrocky92:1.0
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /pod-data/index.html;
          sleep 30;
        done