apiVersion: v1
kind: PersistentVolume
metadata:
  name: lv-local-pv
spec:
  capacity:
    storage: 1G
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lv-local-storage
  local:
    path: /mnt/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kworker-1
          - kworker-2