apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mit-dev-binding
  namespace: default
subjects:
- kind: User
  name: mit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole 
  name: developer
  apiGroup: rbac.authorization.k8s.io