kind: Pod
apiVersion: v1
metadata:
  name: secret-nginx
  labels:
    app: nginx
spec:
  containers:
  - name: secretnginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/lvsecret
  nodeSelector:
    disktype: local
  volumes:
  - name: secret-vol
    secret:
      secretName: lv-app-secret