# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX_IMAGE = "generic/rocky8"
VM_GROUP_NAME = "/VAGRANT-K8S"

MASTER_NODE_COUNT = 1
MASTER_NODE_CPUS = 2
MASTER_NODE_MEMORY = 2048

WORKER_NODE_COUNT = 2
WORKER_NODE_CPUS = 2
WORKER_NODE_MEMORY = 2048

Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Node
  (1..MASTER_NODE_COUNT).each do |masterno|

    config.vm.define "master-#{masterno}" do |node|
      node.vm.box = VAGRANT_BOX_IMAGE
      node.vm.hostname = "master-#{masterno}"
      node.disksize.size = "30GB"
      node.vm.network :private_network, ip: "192.168.56.20#{masterno}"
  
      node.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--groups", VM_GROUP_NAME]
        vbox.customize ["modifyvm", :id, "--cpus", MASTER_NODE_CPUS]
        vbox.customize ["modifyvm", :id, "--memory", MASTER_NODE_MEMORY]
        vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

    node.vm.provision "shell", path: "bootstrap_kmaster.sh"

    end

  end

  # Kubernetes Worker Nodes
  (1..WORKER_NODE_COUNT).each do |workerno|

    config.vm.define "worker-#{workerno}" do |node|
      node.vm.box = VAGRANT_BOX_IMAGE
      node.vm.hostname = "worker-#{workerno}"
      node.disksize.size = "30GB"
      node.vm.network :private_network, ip: "192.168.56.21#{workerno}"
  
      node.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--groups", VM_GROUP_NAME]
        vbox.customize ["modifyvm", :id, "--cpus", WORKER_NODE_CPUS]
        vbox.customize ["modifyvm", :id, "--memory", WORKER_NODE_MEMORY]
        vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      node.vm.provision "shell", path: "bootstrap_kworker.sh"
  
    end

  end

end